(() => {
  const cfg=window.FUTURE_PHARMA_CONFIG||{},key=cfg.supabasePublishableKey||cfg.supabaseAnonKey;
  if(!window.supabase||!cfg.supabaseUrl||!key)return;
  const db=window.supabase.createClient(cfg.supabaseUrl,key),view=()=>document.querySelector('#view');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>'Rs '+Number(n||0).toLocaleString('en-PK',{maximumFractionDigits:2});
  const today=()=>new Date().toISOString().slice(0,10);let profile=null,staff=null,activePage='home',draftId=null,requestKey=null,lines=[];
  function toast(msg){const t=document.querySelector('#toast');if(t){t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),3500)}}
  function nav(){const n=document.querySelector('#navigation');if(!n)return;n.innerHTML='';const items=[['home','Home','⌂'],['new','New order','＋'],['drafts','Drafts','◷'],['confirmed','Confirmed','✓'],['submitted','Submitted','↗'],['previous','Previous','▤'],['profile','Profile','♙']];for(const [id,label,icon] of items){const b=document.createElement('button');b.className='nav';b.dataset.staffPage=id;b.innerHTML=`${icon} <span>${label}</span>`;n.append(b)}const logout=document.querySelector('#logout');if(logout){logout.innerHTML='⇥ <span>Logout</span>';logout.classList.add('nav');n.append(logout)}const brand=document.querySelector('.brand b');if(brand)brand.textContent='FUTURE PHARMA · STAFF';document.querySelector('#roleLabel')?.replaceChildren(document.createTextNode('Staff account'));document.querySelector('#greeting').textContent='Assalamualaikum, '+(profile.username||staff.email?.split('@')[0]||'Staff');document.body.classList.add('staff-mode');}
  function head(title,sub,action=''){return `<div class="staff-head"><div><span class="eyebrow">FUTURE PHARMA · STAFF</span><h1>${title}</h1><p>${sub}</p></div>${action}</div>`}
  async function getOrders(){const {data,error}=await db.from('orders').select('*').order('created_at',{ascending:false});if(error)throw error;return data||[]}
  async function render(page='home'){activePage=page;document.querySelectorAll('[data-staff-page]').forEach(x=>x.classList.toggle('active',x.dataset.staffPage===page));view().innerHTML='<div class="panel empty">Loading your work…</div>';try{if(page==='home')return await dashboard();if(page==='new')return editor();if(page==='drafts')return orderList(['DRAFT'],'My draft orders');if(page==='confirmed')return orderList(['CONFIRMED'],'My confirmed orders');if(page==='submitted')return orderList(['SUBMITTED','PROCESSING','APPROVED'],'Orders sent to Admin');if(page==='previous')return orderList(['COMPLETED','REJECTED','CANCELLED','Delivered'],'Previous orders');if(page==='profile')return profilePage();}catch(e){view().innerHTML=`<section class="panel empty"><b>Couldn't load this page</b><p>${esc(e.message)}</p><button class="btn" data-staff="retry">Try again</button></section>`}}
  async function dashboard(){const os=await getOrders(),mine=os.filter(o=>o.created_by===staff.id),count=s=>mine.filter(o=>o.status===s).length;const t=mine.filter(o=>o.order_date===today()).length;view().innerHTML=head('Good day, '+esc(profile.username||'Staff'),'Yahan se apne orders tayyar karein aur status track karein.',`<button class="btn primary" data-staff="new">＋ New order</button>`)+`<div class="cards staff-cards"><div class="card"><div class="metric-label">Drafts</div><div class="metric">${count('DRAFT')}</div><div class="sub">Still editable</div></div><div class="card"><div class="metric-label">Confirmed</div><div class="metric">${count('CONFIRMED')}</div><div class="sub">Ready to send</div></div><div class="card"><div class="metric-label">Submitted</div><div class="metric">${count('SUBMITTED')+count('PROCESSING')+count('APPROVED')}</div><div class="sub">Received by Admin</div></div><div class="card"><div class="metric-label">Today</div><div class="metric">${t}</div><div class="sub">Orders you created today</div></div></div><section class="panel staff-welcome"><div class="welcome-icon">✚</div><div><h2>Your orders, your workflow</h2><p>Save an order as a draft, check every line, confirm to lock it, then send it to Admin when ready.</p></div><button class="btn" data-staff-page="drafts">Open drafts →</button></section>`}
  async function orderList(statuses,title){const os=(await getOrders()).filter(o=>statuses.includes(o.status));view().innerHTML=head(title,`${os.length} orders in this list`)+`<section class="panel"><div class="tablewrap"><table class="staff-table"><thead><tr><th>Order</th><th>Date</th><th>Customer</th><th>Area / Sector</th><th>Products</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>${os.map(o=>`<tr><td><b>${esc(o.invoice_no||o.order_no)}</b></td><td>${esc(o.order_date)}</td><td>${esc(o.customer_name_snapshot||'Customer')}</td><td>${esc(o.customer_area_snapshot||'—')} / ${esc(o.customer_sector_snapshot||'—')}</td><td>${Number(o.item_count||0)}</td><td>${money(o.net_total||o.total)}</td><td><span class="pill ${o.status==='DRAFT'?'warn':''}">${esc(o.status)}</span></td><td><button class="textbtn" data-staff="view" data-id="${o.id}">View</button>${o.status==='DRAFT'?`<button class="textbtn" data-staff="edit" data-id="${o.id}">Edit</button><button class="textbtn" data-staff="confirm" data-id="${o.id}">Confirm</button>`:''}${o.status==='CONFIRMED'?`<button class="textbtn" data-staff="send" data-id="${o.id}">Send to Admin</button>`:''}</td></tr>`).join('')||`<tr><td colspan="8" class="empty">Nothing here yet.</td></tr>`}</tbody></table></div></section>`}
  async function profilePage(){view().innerHTML=head('My account','Your staff account details.')+`<section class="panel staff-profile"><div class="profile-mark">${esc((profile.username||'S').slice(0,1).toUpperCase())}</div><h2>${esc(profile.username||'Staff')}</h2><p>Staff account · FUTURE PHARMA</p><dl><dt>Login email</dt><dd>${esc(staff.email||'—')}</dd><dt>Role</dt><dd>Staff</dd><dt>Orders created</dt><dd>${(await getOrders()).length}</dd></dl><button class="btn" id="staffLogout">Logout</button></section>`}
  const input=(label,name,type='text',value='',required=false)=>`<label class="field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}></label>`;
  function select(label,name,items,value='',required=true){return `<label class="field">${label}<select name="${name}" ${required?'required':''}><option value="">Choose ${label.toLowerCase()}</option>${items.map(x=>`<option value="${x.id}" ${value===x.id?'selected':''}>${esc(x.label||x.name)}</option>`).join('')}</select></label>`}
  async function editor(id=null){draftId=id;requestKey=id||crypto.randomUUID();lines=[];let old=null;if(id){const [{data,error},it]=await Promise.all([db.from('orders').select('*').eq('id',id).single(),db.from('order_items').select('*').eq('order_id',id)]);if(error)throw error;if(data.status!=='DRAFT')throw Error('This order is locked and cannot be edited.');old=data;lines=(it.data||[]).map(x=>({product_id:x.product_id,name:x.product_name,code:x.product_code,price:Number(x.sale_price),qty:Number(x.qty),discount:Number(x.discount_percent||0),bonus:Number(x.bonus_qty||0)}));}
    const [cs,areas,sectors,products]=await Promise.all([db.from('customers').select('*').eq('active',true).order('name'),db.from('areas').select('*').eq('active',true).order('name'),db.from('sectors').select('*').eq('active',true).order('name'),db.from('products').select('*').eq('active',true).order('name')]);for(const x of [cs,areas,sectors,products])if(x.error)throw x.error;
    const cust=cs.data||[],aa=areas.data||[],ss=sectors.data||[],ps=products.data||[];const areaOpts=aa.map(x=>({id:x.id,name:x.name})),sectorOpts=ss.filter(x=>!old||x.area_id===old.area_id).map(x=>({id:x.id,name:x.name})),custOpts=cust.map(x=>({id:x.id,label:(x.customer_code?x.customer_code+' · ':'')+x.name}));
    view().innerHTML=head(id?'Edit draft':'New order','Select an existing customer and products. Saving keeps this order as your private draft.')+`<form id="staffOrderForm" class="panel staff-order-form"><div class="staff-form-grid">${select('Area','area_id',areaOpts,old?.area_id||'')}${select('Sector','sector_id',sectorOpts,old?.sector_id||'')}${select('Customer','customer_id',custOpts,old?.customer_id||'')}${input('Order date','order_date','date',old?.order_date||today(),true)}<label class="field staff-full">Order note<input name="remarks" value="${esc(old?.remarks||old?.notes||'')}" placeholder="Optional note"></label></div><div class="staff-form-subhead"><div><h2>Add products</h2><p>Search by product name or code.</p></div></div><label class="field"><span class="sr-only">Search product</span><input id="staffProductSearch" placeholder="Search product…" autocomplete="off"></label><div id="staffProductResults" class="staff-product-results"></div><div class="staff-form-subhead"><div><h2>Review items</h2><p>Check price, quantity and discount before saving.</p></div></div><div id="staffLines"></div><div class="staff-total" id="staffTotal"></div><div class="staff-form-actions"><button type="button" class="btn" data-staff="cancel-editor">Cancel</button><button type="button" class="btn" data-staff="save-draft">Save draft</button><button type="button" class="btn primary" data-staff="confirm-draft">Save & review order</button></div></form>`;
    const form=document.querySelector('#staffOrderForm'),area=form.elements.area_id,sector=form.elements.sector_id,customer=form.elements.customer_id;
    area.addEventListener('change',()=>{sector.innerHTML='<option value="">Choose sector</option>'+ss.filter(s=>s.area_id===area.value).map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');customer.innerHTML='<option value="">Choose customer</option>';});
    sector.addEventListener('change',()=>{customer.innerHTML='<option value="">Choose customer</option>'+cust.filter(c=>c.area_id===area.value&&c.sector_id===sector.value).map(c=>`<option value="${c.id}">${esc((c.customer_code?c.customer_code+' · ':'')+c.name)}</option>`).join('');});
    if(old){area.value=old.area_id||'';sector.value=old.sector_id||'';customer.value=old.customer_id||'';}
    document.querySelector('#staffProductResults').addEventListener('click',e=>{const b=e.target.closest('[data-staff-add-product]');if(!b)return;const p=ps.find(x=>x.id===b.dataset.staffAddProduct);if(!p)return;const existing=lines.find(x=>x.product_id===p.id);if(existing)existing.qty++;else lines.push({product_id:p.id,name:p.name,code:p.product_code||p.sku||'',price:Number(p.sale_price),qty:1,discount:Number(p.default_discount||0),bonus:Number(p.default_bonus||0)});drawLines(ps);});
    document.querySelector('#staffProductSearch').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();document.querySelector('#staffProductResults').innerHTML=q?ps.filter(p=>(p.name+' '+p.sku+' '+p.product_code+' '+p.company).toLowerCase().includes(q)).slice(0,12).map(p=>`<button type="button" class="staff-product-hit" data-staff-add-product="${p.id}"><b>${esc(p.name)}</b><span>${esc(p.product_code||p.sku||'')} · ${money(p.sale_price)} · ${Number(p.default_discount||0)}% discount</span></button>`).join('')||'<p class="sub">No matching products.</p>':'';});drawLines(ps);
  }
  function drawLines(products=[]){const box=document.querySelector('#staffLines');if(!box)return;box.innerHTML=lines.map((x,i)=>`<div class="staff-line"><div class="staff-line-main"><b>${esc(x.name)}</b><small>${esc(x.code||'')}</small></div><label>Qty<input type="number" min="1" step="1" data-line="${i}" data-key="qty" value="${x.qty}"></label><label>Price<input type="number" min="0" step="0.01" data-line="${i}" data-key="price" value="${x.price}"></label><label>Discount %<input type="number" min="0" max="100" step="0.01" data-line="${i}" data-key="discount" value="${x.discount}"></label><b>${money(x.qty*x.price*(1-x.discount/100))}</b><button type="button" class="textbtn delete" data-staff-remove-line="${i}">Remove</button></div>`).join('')||'<p class="empty">Add at least one product to this order.</p>';const gross=lines.reduce((n,x)=>n+x.qty*x.price,0),discount=lines.reduce((n,x)=>n+x.qty*x.price*x.discount/100,0);document.querySelector('#staffTotal').innerHTML=`<span>Subtotal ${money(gross)}</span><span>Discount ${money(discount)}</span><strong>Total ${money(gross-discount)}</strong>`;box.onchange=e=>{const i=Number(e.target.dataset.line),key=e.target.dataset.key;if(!Number.isInteger(i)||!key)return;lines[i][key]=Number(e.target.value||0);drawLines(products);};box.onclick=e=>{const b=e.target.closest('[data-staff-remove-line]');if(b){lines.splice(Number(b.dataset.staffRemoveLine),1);drawLines(products);}};}
  async function saveDraft(reviewAfterSave=false){const form=document.querySelector('#staffOrderForm');if(!form.reportValidity())return;if(!lines.length){toast('Add at least one product first.');return;}const values=Object.fromEntries(new FormData(form));const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{const {data,error}=await db.rpc('save_future_pharma_draft',{p_order_id:draftId,p_request_key:requestKey,p_customer_id:values.customer_id,p_area_id:values.area_id,p_sector_id:values.sector_id,p_order_date:values.order_date,p_remarks:values.remarks||'',p_items:lines.map(x=>({product_id:x.product_id,qty:x.qty,price:x.price,discount_percent:x.discount,bonus_qty:x.bonus}))});if(error)throw error;draftId=data;if(reviewAfterSave){toast('Draft saved. Review all details before confirming.');return reviewDraft(draftId);}toast('Draft saved. It has not been sent to Admin.');return editor(draftId);}catch(e){toast(e.message||'Draft save failed. Try again.');buttons.forEach(b=>b.disabled=false);}}
  async function reviewDraft(id){const [{data:o,error},it]=await Promise.all([db.from('orders').select('*').eq('id',id).single(),db.from('order_items').select('*').eq('order_id',id)]);if(error)throw error;if(it.error)throw it.error;if(o.status!=='DRAFT')throw Error('This order is no longer an editable draft.');const items=it.data||[];view().innerHTML=head('Review your order','Check customer, Area, Sector, date, quantities, prices, discounts and total before locking it.')+`<section class="panel staff-review"><div class="review-grid"><div><small>Customer</small><b>${esc(o.customer_name_snapshot||'')}</b><span>Code: ${esc(o.customer_code_snapshot||'')}</span></div><div><small>Area / Sector</small><b>${esc(o.customer_area_snapshot||'—')} / ${esc(o.customer_sector_snapshot||'—')}</b></div><div><small>Order date</small><b>${esc(o.order_date)}</b></div><div><small>Order note</small><b>${esc(o.remarks||'—')}</b></div></div><h2>Products</h2><div class="tablewrap"><table class="staff-table"><thead><tr><th>Product</th><th>Price</th><th>Quantity</th><th>Discount</th><th>Subtotal</th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.product_name)}<div class="sub">${esc(x.product_code||'')}</div></td><td>${money(x.sale_price)}</td><td>${x.qty}</td><td>${Number(x.discount_percent||0)}%</td><td>${money(x.net_amount||x.total)}</td></tr>`).join('')||'<tr><td colspan="5">No items. Go back and add products.</td></tr>'}</tbody></table></div><div class="staff-total"><span>Subtotal ${money(o.gross_total||0)}</span><span>Discount ${money(o.discount_total||0)}</span><strong>Final total ${money(o.net_total||o.total)}</strong></div><p class="notice">After confirmation, this order will be locked and you cannot edit it. It will still not go to Admin until you press “Send to Admin”.</p><div class="staff-form-actions"><button class="btn" data-staff="edit" data-id="${o.id}">Back and edit</button><button class="btn primary" data-staff="confirm-final" data-id="${o.id}">Confirm order and lock</button></div></section>`;}
  async function confirmDraft(id,b){if(!window.confirm('Please review your order carefully. After confirmation, it will be locked and cannot normally be edited. Confirm and lock this order?'))return;b.disabled=true;const {error}=await db.rpc('confirm_future_pharma_order',{p_order_id:id});if(error){b.disabled=false;toast(error.message);return;}toast('Order confirmed and locked. It is not sent to Admin yet.');return render('confirmed');}
  async function send(id){if(!window.confirm('Are you sure you want to send this order to Admin? After submission, you will not be able to modify it.'))return;const {error}=await db.rpc('submit_future_pharma_order',{p_order_id:id});if(error){toast(error.message+' You can retry from Confirmed.');return;}toast('Order submitted to Admin.');render('submitted');}
  async function viewOrder(id,locked=false){const [{data:o,error},it]=await Promise.all([db.from('orders').select('*').eq('id',id).single(),db.from('order_items').select('*').eq('order_id',id)]);if(error)throw error;const items=it.data||[];view().innerHTML=head('Order '+esc(o.invoice_no||o.order_no),`Status: ${esc(o.status)} · ${esc(o.order_date)}`)+`<section class="panel staff-review"><div class="review-grid"><div><small>Customer</small><b>${esc(o.customer_name_snapshot||'')}</b><span>${esc(o.customer_code_snapshot||'')}</span></div><div><small>Area / Sector</small><b>${esc(o.customer_area_snapshot||'—')} / ${esc(o.customer_sector_snapshot||'—')}</b></div></div><h2>Products</h2><div class="tablewrap"><table class="staff-table"><thead><tr><th>Product</th><th>Qty</th><th>Price</th><th>Discount</th><th>Total</th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.product_name)}</td><td>${x.qty}</td><td>${money(x.sale_price)}</td><td>${Number(x.discount_percent||0)}%</td><td>${money(x.net_amount||x.total)}</td></tr>`).join('')}</tbody></table></div><div class="staff-total"><span>Subtotal ${money(o.gross_total||o.total)}</span><span>Discount ${money(o.discount_total)}</span><strong>Total ${money(o.net_total||o.total)}</strong></div><p>${esc(o.remarks||o.notes||'')}</p><div class="staff-form-actions"><button class="btn" data-staff-page="${o.status==='DRAFT'?'drafts':o.status==='CONFIRMED'?'confirmed':'submitted'}">Back</button>${o.status==='DRAFT'?`<button class="btn" data-staff="edit" data-id="${o.id}">Edit draft</button>`:''}${o.status==='CONFIRMED'?`<button class="btn primary" data-staff="send" data-id="${o.id}">Send to Admin</button>`:''}</div></section>`}
  async function staffAction(b){const a=b.dataset.staff,id=b.dataset.id;try{if(a==='new')return editor();if(a==='edit')return editor(id);if(a==='view')return viewOrder(id);if(a==='save-draft')return saveDraft(false);if(a==='confirm-draft')return saveDraft(true);if(a==='confirm-final')return confirmDraft(id,b);if(a==='send')return send(id);if(a==='cancel-editor')return render('drafts');if(a==='retry')return render(activePage);if(a==='logout')return db.auth.signOut();}catch(e){toast(e.message)}}
  async function activate(user){staff=user;const {data,error}=await db.from('profiles').select('username,role').eq('id',user.id).single();if(error||!data||data.role!=='staff')return;profile=data;nav();await render('home');}
  document.addEventListener('click',e=>{const sf=e.target.closest('[data-staff-page]');if(sf){e.preventDefault();e.stopImmediatePropagation();render(sf.dataset.staffPage);return;}const add=e.target.closest('[data-staff-add-product]');if(add){e.preventDefault();return;}const remove=e.target.closest('[data-staff-remove-line]');if(remove){e.preventDefault();return;}const b=e.target.closest('[data-staff]');if(b){e.preventDefault();e.stopImmediatePropagation();staffAction(b);}},true);
  db.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'&&session?.user)setTimeout(()=>activate(session.user),0);if(event==='SIGNED_OUT')document.body.classList.remove('staff-mode');});
  db.auth.getSession().then(({data})=>{if(data.session?.user)activate(data.session.user)});
})();
